apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kbot
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: kbot
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
