apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      port: 8889 
      targetPort: 8889
  type: ClusterIP
