apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kbot
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: kbot
        namespace: flux-system
      version: "*"
      reconcileStrategy: ChartVersion
  values:
    image:
      registry: ghcr.io
      repository: armrcode/kbot
      tag: latest
      pullPolicy: IfNotPresent
      os: linux
      arch: ""
    replicaCount: 1
    ingress:
      enabled: false
    service:
      type: ClusterIP
      port: 8080
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
    serviceAccount:
      create: true
      name: kbot
    secret:
      name: kbot
      tokenName: TELE_TOKEN
      tokenKey: token