replicaCount: 1
image:
  registry: ghcr.io
  repository: armrcode/kbot
  tag: ""
  pullPolicy: IfNotPresent
  os: linux
  arch: arm64
secret:
  name: kbot
  tokenName: TELE_TOKEN
  tokenKey: token
service:
  type: ClusterIP
  port: 8080
serviceAccount:
  create: true
  name: ""
ingress:
  enabled: false
