replicaCount: 1
image:
  registry: ghcr.io
  repository: armrcode/kbot
  tag: v1.0.0-d42b2f6
  pullPolicy: IfNotPresent
  os: linux
  arch: ""
secret:
  name: kbot
  tokenName: TELE_TOKEN
  tokenKey: token
service:
  type: ClusterIP
  port: 8080
serviceAccount:
  create: true
  name: ""
ingress:
  enabled: false
