name: CI/CD

on:
  push:
    branches:
      - develop

env:
  TARGETOS: linux
  TARGETARCH: amd64
  CGO_ENABLED: 0

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - name: Build binary
        run: make build TARGETOS=${{ env.TARGETOS }} TARGETARCH=${{ env.TARGETARCH }}

  docker:
    name: Build & Push Docker Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo v1.0.0)-$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: armrcode
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          make image push \
            TARGETOS=${{ env.TARGETOS }} \
            TARGETARCH=${{ env.TARGETARCH }} \
            VERSION=${{ env.VERSION }}

      - name: Update Helm chart
        run: |
          # Обновляем tag и arch в helm/values.yaml
          yq -i ".image.tag = \"${VERSION}\" | .image.arch = \"${TARGETARCH}\"" helm/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/values.yaml
          git commit -m "chore: update Helm image tag to ${VERSION}" || echo "No changes to commit"
          git push https://armrcode:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:develop || echo "No changes to push"

      - name: Cleanup
        run: make clean TARGETARCH=${{ env.TARGETARCH }}
