name: KBOT-CICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  TARGETARCH: amd64
  TARGETOS: linux
  CGO_ENABLED: 0

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      # - name: Run tests
      #   run: make test

      - name: Build
        run: make build TARGETARCH=${{ env.TARGETARCH }} TARGETOS=${{ env.TARGETOS }}

  cd:
    name: CD
    needs: ci
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          cache: true

      - name: Set version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo v1.0.0)-$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Hub image
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          make image push \
            TARGETARCH=${{ env.TARGETARCH }} \
            TARGETOS=${{ env.TARGETOS }} \
            VERSION=${{ env.VERSION }} \
            REGISTRY=docker.io/${{ secrets.DOCKERHUB_USERNAME }}

      - name: GitHub Container Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push GHCR image
        env:
          APP: "kbot"
          REGISTRY: ghcr.io/${{ github.repository_owner }}
        run: |
          make image push \
            TARGETARCH=${{ env.TARGETARCH }} \
            TARGETOS=${{ env.TARGETOS }} \
            VERSION=${{ env.VERSION }} \
            REGISTRY=ghcr.io/${{ github.repository_owner }}

      - name: Update Helm chart
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

      - name: Commit Helm chart changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add helm/values.yaml
          git commit -m "chore: update version to ${{ env.VERSION }}" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Cleanup
        run: make clean TARGETARCH=${{ env.TARGETARCH }}
